[package]
name = "orbits"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2021"

[dependencies]
ggez = "0.8.1"
rand = "0.8.5"
palette = "0.7.1"
nalgebra = "0.32.2"
