[package]
name = "orbits"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2021"

[dependencies]
#ggez = "0.8.1"
ggez = "0.9.0-rc0"
rand = "0.8.5"
nalgebra = { version = "0.32.2", features = ["mint"] }
rgb_hsv = "1.0.1"